# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-21T17:07:19Z"
  labels:
    app: service-a-test
  name: service-a-test
spec:
  containers:
  - env:
    - name: container
      value: oci
    image: localhost/service-a:latest
    name: service-a
    ports:
    - containerPort: 3000
      hostPort: 3000
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    stdin: true
    workingDir: /
  dnsConfig: {}
status: {}
---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-21T17:07:19Z"
  labels:
    app: service-b-test
  name: service-b-test
spec:
  containers:
  - env:
    - name: container
      value: oci
    image: localhost/service-b:latest
    name: service-b
    ports:
    - containerPort: 3000
      hostPort: 3001
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    stdin: true
    workingDir: /
  dnsConfig: {}
status: {}

